[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

  # This is the corrected syntax for scheduling a specific function
  [functions."fetch-weekly-games"]
    schedule = "59 23 * * 1"
