[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Add this new section to schedule the function
[functions.schedule]
  # This is a cron expression that means "at 11:59 PM on Monday"
  cron = "59 23 * * 1"
  function = "fetch-weekly-games"