# This file configures the build and deployment settings for Netlify.

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

  # --- Function Schedules ---
  [functions."fetch-weekly-games"]
    schedule = "59 23 * * 1" # Monday at 11:59 PM

  [functions."update-live-scores"]
    schedule = "0 * * * 5,6,0" # Every hour on Fri, Sat, Sun
  
  # The other functions are triggered manually, so they have no schedule.

# --- Redirect Rule for Functions ---
# This rule is crucial for the live site. It tells Netlify how to handle
# requests from the frontend to the backend serverless functions.
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
