[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

  [functions."fetch-weekly-games"]
    schedule = "59 23 * * 1"

  [functions."update-live-scores"]
    schedule = "0 * * * 5,6,0"