[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

  # Fetches upcoming games once a week
  [functions."fetch-weekly-games"]
    schedule = "59 23 * * 1" # Monday at 11:59 PM

  # Fetches live scores every hour on the weekend
  [functions."update-live-scores"]
    schedule = "0 * * * 5,6,0" # Every hour on Fri, Sat, Sun

  # This new function settles the weekly results
  [functions."settle-weekly-results"]
    schedule = "0 2 * * 2" # Tuesday at 2:00 AM